# docker-compose.yml
version: '3.7'
services:
  tableau-extension:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    environment:
      - PORT=8080
    command: npm run start
